### ISSUE TITLE
Attempting to run JMH benchmarks always enables annotation processing for main module

### ISSUE THREAD

**Issue by Barteks2x** [artyushov/idea-jmh-plugin#23]
I have annotation processor that won't work in IDEA but also isn't necessary for everything to work and is used only in gradle build, so I have annotation processing disabled. Enabling annotation processing breaks building the project. 

When I try to run any jmh benchmark, the plugin always enabled annotation processing.

**Comment by artyushov** [comment]
Hi.

Jmh requires annotation processor, without it it's not possible to run benchmarks.
The solution would probably be to disable annotation processing after run finishes, but I can't promise that I will implement this any time soon.

**Comment by Barteks2x** [comment]
The problem is that my project won't even compile with annotation processing on, one solution would be to add just the JMH annotation processor to the list instead of letting IDEA detect it automatically.

**Comment by artyushov** [comment]
Have you tried to specify processor path manually in the IDE preferences?

**Comment by Barteks2x** [comment]
This works but it's very confusing and hard to figure out what is wrong when everything just stops working after trying to run JMH benchmark. That's why it would be better to automatically add it to the list,

**Comment by stokito** [comment]
I have no idea how to solve this properly but I added a confirmation message to user "Annotation processing is not enabled but JMH needs to preprocess classes bytecode" so at least we wont confuse user by unexpected behavior.
I'll close the ticket as partially solved but if you have better ideas then feel free to write them here
