### ISSUE TITLE
Configuration of environment variables in Run configuration is lost

### ISSUE THREAD

**Issue by viliam-durina** [artyushov/idea-jmh-plugin#26]
I try to address problem mentioned in issue #19. But after adding the `TMP` environment variable and clicking OK, the variable is missing.

This is with IDEA 2017.1.1 on Windows, I didn't use the plugin before, so I cannot confirm, if the problem was there before.

**Comment by leus** [comment]
Still having this problem with IDEA Community 2017.2.3

Both TEMP and TMP environment variables are properly set. Also, the plugin mindlessly appends "/jmh.lock" to the path; it should probably use `Paths.get(System.getProperty("java.io.tmpdir"), "jmh.lock")`

**Comment by stokito** [comment]
Please try the new version v1.1.0 on IntelliJ 2020.3.
I tested and manually set `TEMP` env and pressed OK, then runned, then restarted IDE but the env is still saved.
So I'll close the ticked but if the issue is still persist for you then please feel free to reopen the ticket.
