### ISSUE TITLE
Different icon than for the regular application run

### ISSUE THREAD

**Issue by szpak** [artyushov/idea-jmh-plugin#29]
The icon used in the JMH plugin executions could be somehow customized to make it clear which type of execution is used (as compared to the regular Application). Having both the main method in a class and the `@Benchark`-annotated methods displays two execution targets (with the same icon).

It's a minor issue as both executions should behave in similar way, but still.

**Comment by stokito** [comment]
JMH doesn't have an own logo and the icons should have dark and light versions. We can use a standard icon from IntelliJ:
https://jetbrains.design/intellij/resources/icons_list/
There is few icons for profilers and profileBlue is used for JFR profiler.
Unless any objections I'll set profileYellow which looks unused.
