### ISSUE TITLE
Run benchmarks from more than one file

### ISSUE THREAD

**Issue by szpak** [artyushov/idea-jmh-plugin#30]
When a few files are selected in a tree view the plugin should pass all the files to the benchmark execution. E.g. I have 5 classes with benchmarks: Benchmark1, Benchmark2, ... . I would like to run just Benchmark1 and Benchmark4. Therefore, after selecting those 2 files and CTRL-SHIFT-F10 they JMH execution file should end with:
`... com.example.Benchmark1.* com.example.Benchmark2.*`
(set as `Program arguments` in the run configuration)

It works fine, when set manually.

**Comment by stokito** [comment]
As far I understood this may be not so easy to implement. I guess most of time developers working on a single benchmark.
I'll close the issue but any PR will be appreciated.
