### ISSUE TITLE
Add regex end of line anchor to method name argument

### ISSUE THREAD

**Issue by hmottestad** [artyushov/idea-jmh-plugin#43]
When running a single benchmark method the plugin adds the full method name as a program argument.

Example: `org.eclipse.rdf4j.sail.memory.benchmark.QueryBenchmark.removeByQuery`

This will also match other methods that start with the same name, ex. `removeByQueryNoIsolation`

The regex end of line anchor `$` can be used to stop this behaviour.

Example: `org.eclipse.rdf4j.sail.memory.benchmark.QueryBenchmark.removeByQuery$`

I'm not sure where to make this change myself.

**Comment by stokito** [comment]
ok, I'll check on a weekend

**Comment by stokito** [comment]
In a day or two the new version will be released, please check. Thank you for the reporting
