### ISSUE TITLE
Implement default run parameters

### ISSUE THREAD

**Issue by artyushov** [artyushov/idea-jmh-plugin#5]

**Comment by meditativeape** [comment]
Hey @artyushov , noticed that this issue has been open for a while. Are you still planning to implement this? I have a few benchmarks that need to read java truststore files from a directory under the module root, but by default the working directory is the project root, so it's quite painful that I have to set the working dir for each individual run configuration. Would be nice if the plugin supports default run parameters.
I'm pretty new to Gradle, but if you're open to pull requests and think this feature is doable for beginners, then I'd be happy to take a shot at it.

**Comment by artyushov** [comment]
Hi!

I'm very sorry for such late response.
Almost all of the issues have been open here for a while, I'm not a responsible maintainer :)
One more problem about this issue is that I'm not really sure myself how to implement it. I guess a menu item should be added to IDE preferences.

This has nothing to do with gradle, it's all about digging into intellij sources. I had no prior knowledge about plugin development when I started it. So it should be doable and I'm absolutely open to pull requests and will promise to be cooperative if you decide to contribute.

**Comment by meditativeape** [comment]
Thanks for the reply, and for pointing me in the right direction. I should have some free time at the end of year, so will dig into the intelliJ world and see what's the right thing to do there. Will keep you updated!

**Comment by sparkoo** [comment]
is it solved by #27 or does this issue need something more?

**Comment by artyushov** [comment]
It is resolved indeed
