### ISSUE TITLE
Can't find the field "Program Arguments" as an option of the run configuration

### ISSUE THREAD

**Issue by lucamolteni** [artyushov/idea-jmh-plugin#52]
Previous IDEA: 

![Previous run configuration](https://github.com/user-attachments/assets/daae2269-44bf-45b0-a2c2-dacb7455faa9)

Idea 2024.1.4

<img width="817" alt="Screenshot 2024-09-12 at 16 51 32" src="https://github.com/user-attachments/assets/578a10ef-aa27-4666-9033-793f8abfbb38">

<img width="768" alt="Screenshot 2024-09-12 at 16 56 13" src="https://github.com/user-attachments/assets/73204296-ef71-4669-a6d3-2fc7f1a8c603">

**Comment by mariofusco** [comment]
+1 I'm experiencing exactly the same problem.

**Comment by stokito** [comment]
JB changed API and I didn't had enough aspiration to find how to migrate to the new API.

How critical is this? Which arguments you are usually using? The `prof perf stat`, maybe something else? I'm asking because maybe we can add the arg as a checkbox.

**Comment by lucamolteni** [comment]
> JB changed API and I didn't had enough aspiration to find how to migrate to the new API.
> 
> How critical is this? Which arguments you are usually using? The `prof perf stat`, maybe something else? I'm asking because maybe we can add the arg as a checkbox.

There's a workaround, that is to create a main configuration with either the JMH Main or a main created inside the benchmark class but yes, it's mostly to add profiling

<img width="543" alt="Screenshot 2024-09-13 at 10 04 59" src="https://github.com/user-attachments/assets/1e16e137-ae99-4de3-ba44-d1164f2f873b">

<img width="541" alt="Screenshot 2024-09-13 at 10 05 05" src="https://github.com/user-attachments/assets/6926e09e-f15f-4096-9bef-a79b8ed8f351">

**Comment by stokito** [comment]
A created the new release so in a few days it will be published.
The additional options for the profile have to be implemented in scope of #36 or #42
